apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
      - image: 418295704289.dkr.ecr.us-west-1.amazonaws.com/student-backend:latest
        name: backend
        ports:
        - containerPort: 3000
